-- MySQL Script generated by MySQL Workbench
-- Tue Mar 23 11:25:37 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema licoreria_inventario
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema licoreria_inventario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `licoreria_inventario` DEFAULT CHARACTER SET utf8 ;
USE `licoreria_inventario` ;

-- -----------------------------------------------------
-- Table `licoreria_inventario`.`Proveedores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `licoreria_inventario`.`Proveedores` ;

CREATE TABLE IF NOT EXISTS `licoreria_inventario`.`Proveedores` (
  `idProveedores` VARCHAR(45) NOT NULL,
  `Nombre_proveedores` VARCHAR(45) NOT NULL,
  `Telefono_proveedores` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProveedores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `licoreria_inventario`.`Productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `licoreria_inventario`.`Productos` ;

CREATE TABLE IF NOT EXISTS `licoreria_inventario`.`Productos` (
  `idProductos` INT NOT NULL AUTO_INCREMENT,
  `Nombre_producto` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Cantidad` INT(11) NOT NULL,
  `Tamaño` VARCHAR(45) NOT NULL,
  `Grados_alcohol` VARCHAR(45) NOT NULL,
  `Estado` VARCHAR(45) NOT NULL,
  `Proveedores_idProveedores` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProductos`),
  INDEX `fk_Productos_Proveedores1_idx` (`Proveedores_idProveedores` ASC) VISIBLE,
  CONSTRAINT `fk_Productos_Proveedores1`
    FOREIGN KEY (`Proveedores_idProveedores`)
    REFERENCES `licoreria_inventario`.`Proveedores` (`idProveedores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `licoreria_inventario`.`Ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `licoreria_inventario`.`Ventas` ;

CREATE TABLE IF NOT EXISTS `licoreria_inventario`.`Ventas` (
  `idVentas` INT NOT NULL AUTO_INCREMENT,
  `Fecha_venta` DATE NOT NULL,
  `Cantidad vendida` INT(11) NOT NULL,
  `Productos_idProductos` INT NOT NULL,
  `Valor` INT(11) NOT NULL,
  PRIMARY KEY (`idVentas`),
  INDEX `fk_Ventas_Productos_idx` (`Productos_idProductos` ASC) VISIBLE,
  CONSTRAINT `fk_Ventas_Productos`
    FOREIGN KEY (`Productos_idProductos`)
    REFERENCES `licoreria_inventario`.`Productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `licoreria_inventario`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `licoreria_inventario`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `licoreria_inventario`.`Usuario` (
  `idUsuario` VARCHAR(45) NOT NULL,
  `PassUsuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
